### ISSUE TITLE
review operational activities

### ISSUE THREAD

**Issue by ramyasghub** [SBTCN/tanga2#13]

**Comment by ramyasghub** [comment]
@generalseven Shekhar's work activity follow up : techpack # 
- raiyatex bd #89 , 
- hello introduction mail format #88 , 
- advance planning december 2021 #87 ,

**Comment by generalseven** [comment]
This listing is pointless.  It gives no information.  I can look at the
relevant issue #s.

**Comment by generalseven** [comment]
What did you do related to this issue today?  If there is nothing delivered, you did not work on it.

**Comment by generalseven** [comment]
You can't declare an issue without updating in the issue what you accomplished with notes and deliverables.

**Comment by ramyasghub** [comment]
@generalseven This is an ongoing task. Can this be assigned to new milestone ? BTC1W#103

**Comment by generalseven** [comment]
Do not reopen issues.
