### ISSUE TITLE
improve onboarding

### ISSUE THREAD

**Issue by ramyasghub** [SBTCN/tanga2#14]

**Comment by generalseven** [comment]
standard onboarding so that

Advance planning
Estimates
Targets
Approval completed quickly and easily so new recruits get started easily

**Comment by ramyasghub** [comment]
@generalseven - Could you add Shagun to the project / workspace to align & coordinate the next sequential steps

**Comment by ramyasghub** [comment]
Please find Richard's comments for the work items.

**Comment by generalseven** [comment]
> @generalseven - Could you add Shagun to the project / workspace to align & coordinate the next sequential steps

You have been added to https://github.com/SBTCN/torna/ for coordinating with them.

**Comment by ramyasghub** [comment]
Coordinated with Shagun on Anand Kumar SEO boarding . Plan submission in review.

**Comment by generalseven** [comment]
@ramyasghub status? what means this?

**Comment by ramyasghub** [comment]
@generalseven - Anand SEO has submitted a revised plan. Work in progress

**Comment by ramyasghub** [comment]
@generalseven Please find attachment 
[Bitcoin Wednesday SEO - Advance Planning_______ _______ _______ (2).xlsx](https://github.com/SBTCN/tanga2/files/7587794/Bitcoin.Wednesday.SEO.-.Advance.Planning_______._______._______.2.xlsx)

**Comment by generalseven** [comment]
As discussed.  @ramyasghub this is not an improvement.  The requested corrections must be made or this cannot be approved.

**Comment by ramyasghub** [comment]
@generalseven  Discussed with SEO candidate-Abhishek ; detail planning sent

**Comment by ramyasghub** [comment]
@generalseven Discussed with SEO candidate-Sujoy ; detail planning sent

**Comment by ramyasghub** [comment]
@generalseven Review SEO candidate Abhishek detail planning. 
He is confident, handles the task but not specific 
Requested for a simplified version
[Abhishek SEO-Advance-Planning.xlsx](https://github.com/SBTCN/tanga2/files/7639569/Abhishek.SEO-Advance-Planning.xlsx)

**Comment by generalseven** [comment]
@ramyasghub this can better be added to torna#102

**Comment by generalseven** [comment]
> Discussed with SEO candidate-Sujoy ; detail planning sent

Where is this one?

**Comment by ramyasghub** [comment]
@generalseven Detail planning of Sujoy attached
Unsure,  
Requested to give examples on the findings
[Sujoy SEO-Advance-Planning (4).xlsx](https://github.com/SBTCN/tanga2/files/7642078/Sujoy.SEO-Advance-Planning.4.xlsx)

**Comment by generalseven** [comment]
@ramyasghub this too can better be added to torna#102

**Comment by ramyasghub** [comment]
related issue closed
