### ISSUE TITLE
report absence of members in advance to HR & operation leads

### ISSUE THREAD

**Issue by ramyasghub** [SBTCN/tanga2#16]

**Comment by generalseven** [comment]
What is the plan for doing this?

You can occasionally do spot checks on team members and report on their
time to respond.  However, it is best to look at their actual progress.

When progress is insufficient, then required detailled specification hour
by hour.

**Comment by ramyasghub** [comment]
Have Absence report. Update planning & revise to meet progress. Confirm
from team member on daily updates and meetings

**Comment by generalseven** [comment]
> Confirm from team member on daily updates and meetings

Let me know what this adds about activity that we don't already get from
their performance tracking.  Team members will generally self-report 100%
although detail specifications, deliverables and results tell a different
story.
