### ISSUE TITLE
track performance ramya dec 2021

### ISSUE THREAD

**Issue by ramyasghub** [SBTCN/tanga2#26]
issue # | status | % done today | % still to do | delivery date
-- | -- | -- | -- | --
#13 | in progress | 50% | 50% | 03.12.21    
#14 | in progress | 40% | 60% | 05.12.21    

Links to issues # 
#102
SBTCN/torna#102

#108
SBTCN/techpack#108

#87
SBTCN/techpack#87

**Comment by ramyasghub** [comment]
issue # | status | % done today | % still to do | delivery date
-- | -- | -- | -- | --
#13 | in progress | 60% | 40% | 05.12.21    
#14 | in progress | 45% | 55% | 25.12.21    

Links to issues # 
#102
SBTCN/torna#102
#137
SBTCN/torna#137
#108
SBTCN/techpack#108
#87
SBTCN/techpack#87

**Comment by ramyasghub** [comment]
issue # | status | % done today | % still to do | delivery date
-- | -- | -- | -- | --
#13 | in progress | 30% | 70% | 10.12.21    
#14 | in progress | 50% | 50% | 10.12.21    

Links to issues # 
#149
SBTCN/torna#149

#89 to 94
SBTCN/techpack#89
SBTCN/techpack#90
SBTCN/techpack#91
SBTCN/techpack#92
SBTCN/techpack#93
SBTCN/techpack#94

**Comment by ramyasghub** [comment]
issue # | status | % done today | % still to do | delivery date
-- | -- | -- | -- | --
#13 | in progress | 35% | 65% | 10.12.21    
#14 | in progress | 50% | 50% | 10.12.21    

SBTCN/tanga#2
SBTCN/torna#137
Mails & What's app updates 
SBTCN/techpack#90, #83, #92

**Comment by generalseven** [comment]
> SBTCN/techpack#90, SBTCN/techpack#83, SBTCN/techpack#92

I don't see much of your contribution in the above techpack issues.  How much time did you actually spend on these items and what exactly did you do other than a quick reply in the relevant issue?

SBTCN/torna#137  Same comment as above.

#14 states that you have worked on 50% of the above issue today.  What exactly did you do on this issue today?  I see no evidence of your contribution in the issue.

#13  Similar comment as above. What exactly did you do on this issue today?  35%?  What did you do and how much time did it take you?  I see documentation of that.

Please fix urgently.

**Comment by ramyasghub** [comment]
issue # | status | % done today | % still to do | delivery date
-- | -- | -- | -- | --
#13 | in progress | 15% | 0% | 10.12.21    
#18 | in progress | 10% | 20% | 10.12.21    

SBTCN/tanga2/#26
SBTCN/torna#149
SBTCN/techpack#90, #91, #92

1. review operational activities 
2. review hr activities related to onboarding 
3. Shekhar - guided & assisted

Time spent on workspaces techpack, torna, tanga2 
- 3 hours

**Comment by ramyasghub** [comment]
Thursday, 9-12-21
3:20 hours

issue # | time spent| delivery day | 
-- | -- | -- |
#13  |  3 hour  |  09.12.21    
#18 |  20 min  |  09.12.21    

Ask Shekhar to work on template SBTCN/techpack/#81
Check with him if queries, vendor calls are answered  
Ask techpack process related queries 
Check with bmathuria on SBTCN/torna/#137

**Comment by generalseven** [comment]
It seems you are working part time....

**Comment by generalseven** [comment]
https://github.com/SBTCN/tanga2/issues/26#issuecomment-989813038

You can't declare an issue without updating in the issue what you accomplished with notes and deliverables.

Even worse, urgent issues have not been touched.

**Comment by ramyasghub** [comment]
Thursday, 10-12-21
8 hours

issue # | time spent| delivery day | 
-- | -- | -- |
#13  |  6 hour  |  10.12.21    
#18 |  2 hour |  10.12.21    

SBTCN/torna/#144
SBTCN/techpack/#89 
SBTCN/tanga2/#2
SBTCN/techpack/#85

**Comment by generalseven** [comment]
#13 You did not spend 6 hours on this.  There is no documentation or result to show for it.  Further, the issue was marked yesterday with "You can't declare an issue without updating in the issue what you accomplished with notes and deliverables." and nothing was added and you ignored the urgent issues while that one was marked only with MEDIUM priority.

#18 same.
